version: "3"
services:
  app:
    image: premiummedia/php:${PHP_VERSION}
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
    volumes:
      - './:/var/www/html'
      - './.docker/php/config/conf/general.ini:/usr/local/etc/php/conf.d/general.ini'
      - './.docker/php/config/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini'
      - './.docker/php/config/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './.docker/php/logs/php:/tmp/log/php'
      - './.docker/php/logs/xdebug:/tmp/log/xdebug'
    ports:
      - '${APACHE_PORT_HOST}:80'
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - '${MYSQL_PORT_HOST}:3306'
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "${MAILHOG_SMTP_PORT_HOST}:1025"
      - "${MAILHOG_WEB_PORT_HOST}:8025"
