version: "3"
services:
  nginx:
    image: rstadler333/nginx:latest
    restart: always
    working_dir: /var/www/html
    depends_on:
      - apache
    volumes:
      - './:/var/www/html'
    ports:
      - '${NGINX_PORT_HOST}:80'
  apache:
    image: rstadler333/apache:latest
    restart: always
    working_dir: /var/www/html
    depends_on:
      - php
    volumes:
      - './:/var/www/html'
  php:
    image: rstadler333/php:latest
    restart: always
    working_dir: /var/www/html
    depends_on:
      - mysql
      - mailhog
    volumes:
      - './:/var/www/html'
      - '.docker/php/config/conf/general.ini:/etc/php/7.2/fpm/conf.d/99-general.ini'
      - '.docker/php/config/conf/opcache.ini:/etc/php/7.2/fpm/conf.d/99-opcache.ini'
      - '.docker/php/config/conf/xdebug.ini:/etc/php/7.2/fpm/conf.d/99-xdebug.ini'
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - '${MYSQL_PORT_HOST}:3306'
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  node:
    image: node:${NODE_VERSION}
    user: "node"
    restart: always
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - './:/app'
    command: ["sh", "-c", "yarn && yarn run watch"]
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "${MAILHOG_SMTP_PORT_HOST}:1025"
      - "${MAILHOG_WEB_PORT_HOST}:8025"
