enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  c96d6dc9-685a-459c-9805-052e6e332d7f:
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: '{slug}'
type: channel
